SystemUI: Fix NPE on Volume panel plugins
2020-09-02 20:58:55.035 14263-14263/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.systemui, PID: 14263
    com.android.systemui.shared.plugins.PluginManagerImpl$CrashWhilePluginActiveException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.content.pm.PackageManager.queryIntentServices(android.content.Intent, int)' on a null object reference
        at com.android.systemui.shared.plugins.PluginManagerImpl$PluginExceptionHandler.uncaughtException(PluginManagerImpl.java:426)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:2181)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.content.pm.PackageManager.queryIntentServices(android.content.Intent, int)' on a null object reference
        at com.android.systemui.statusbar.phone.VolumePluginManager.getPluginInfo(VolumePluginManager.java:189)
        at com.android.systemui.statusbar.phone.VolumePluginManager.togglePlugins(VolumePluginManager.java:132)
        at com.android.systemui.statusbar.phone.VolumePluginManager.access$000(VolumePluginManager.java:63)
        at com.android.systemui.statusbar.phone.VolumePluginManager$1.run(VolumePluginManager.java:125)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7398)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
VolumePlugin: Fix another NPE

2020-12-29 17:33:18.885 3441-3441/? W/VolumePluginManager: Error handling overlays.
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.android.systemui.shared.plugins.PluginEnabler.setEnabled(android.content.ComponentName)' on a null object reference
        at com.android.systemui.statusbar.phone.VolumePluginManager.togglePlugins(VolumePluginManager.java:138)
        at com.android.systemui.statusbar.phone.VolumePluginManager.access$000(VolumePluginManager.java:65)
        at com.android.systemui.statusbar.phone.VolumePluginManager$1.run(VolumePluginManager.java:125)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7661)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Signed-off-by: ZeNiXxX <zenixxx.havoc@gmail.com>
Signed-off-by: Hưng Phan <phandinhhungvp2001@gmail.com>